development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: app42_paa_s_rails_couchdb_sample
  suffix: development
  username:
  password:

test:
  <<: *development
  suffix: test

production:
  protocol: 'http'                                               
  host: 192.168.2.153                  # VM IP
  port: 21612                  # VM Port
  prefix: t       # Database Name a/c to prefix and suffix 
#  suffix: production              # Database Name a/c to  prefix and suffix
  username: aq3mu42vtp7tzbj9         # User Name
  password: 'au42frpccq0p90r8cq9pems84ijcme42'        # Password
