development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: app42_paa_s_rails_couchdb_sample
  suffix: development
  username:
  password:

test:
  <<: *development
  suffix: test

production:
  protocol: 'http'                                               
  host: 192.168.2.202                  # VM IP
  port: 50988                  # VM Port
  prefix: t       # Database Name a/c to prefix and suffix 
#  suffix: production              # Database Name a/c to  prefix and suffix
  username: a2gy98xzxicn1ho5         # User Name
  password: 'an1bi65bd3z288f3zqfcg4si1u7l1474'        # Password
